const PRODUCTS = [
  { id: 'p1', category: 'photography', title: 'Kingdom Of Birds', price: 400, img: '/assets/Kingdom Of Birds, Photograph.jpg' },
  { id: 'p2', category: 'paintings', title: 'Divine Horses', price: 450, img: '/assets/Divine Horses- painting.jpg' },
  { id: 'p3', category: 'sculptures', title: 'Funny Snake', price: 600, img: '/assets/Funny Snake Sculpture.jpg' },
  { id: 'p4', category: 'paintings', title: 'Life Full of Colors', price: 400, img: '/assets/Life Full of Colors, Painting.jpg' },
  { id: 'p5', category: 'sculptures', title: 'Lion',  price: 350, img: '/assets/Lion -Sculpture.jpg' },
  { id: 'p6', category: 'photography', title: 'Lion',  price: 1200, img: '/assets/Lion.jpeg' },
  { id: 'p7', category: 'photography', title: 'Lost in the Highlands', price: 400, img: '/assets/Lost in the Highlands, Photograph.jpg' },
  { id: 'p8', category: 'sculptures', title: 'Male Anatomy', price: 500, img: '/assets/Male Anatomy Sculpture.jpg' },
  { id: 'p9', category: 'sculptures', title: 'Own',  price: 600, img: '/assets/Own, Sculpture.jpg' },
  { id: 'p10', category: 'paintings', title: 'RadhaKrishna',  price: 7400, img: '/assets/RadhaKrishna,Painting.jpg' },
  { id: 'p12', category: 'photography', title: 'She Shoal',  price: 900, img: '/assets/She Shoal, Photograph.jpg' },
  { id: 'p13', category: 'sculptures', title: 'Sphinx', price: 800, img: '/assets/Sphinx , Sculpture.jpg' },
  { id: 'p14', category: 'photography', title: 'Tiger',  price: 750, img: '/assets/Tiger, Photograph.jpeg' },
  { id: 'p15', category: 'photography', title: 'Tree',  price: 1000, img: '/assets/tree.jpg' },
  { id: 'p16', category: 'photography', title: 'Villr',  price: 450, img: '/assets/Villr, Photograph.jpg' },
  { id: 'p17', category: 'photography', title: 'Wings Of Light',  price: 1300, img: '/assets/Wings Of Light, Photograph.jpg' },
  { id: 'p18', category: 'paintings', title: 'Waterfall',  price: 900, img: '/assets/Waterfall.jpg' },
  { id: 'p19', category: 'paintings', title: 'Guale 40',  price: 1200, img: '/assets/Guale 40 Painting.jpg' },
  { id: 'p20', category: 'paintings', title: 'Infinite Flow',  price: 700, img: '/assets/Infinite Flow Painting.jpg' },
  { id: 'p21', category: 'paintings', title: 'Spasm For Juanita',  price: 950, img: '/assets/Spasm For Juanita Painting.jpg' },
  { id: 'p22', category: 'paintings', title: 'The Mirror Of The Soul',  price: 1600, img: '/assets/The Mirror Of The Soul Painting.jpg' },
  { id: 'p23', category: 'paintings', title: 'The Room No. 276',  price: 660, img: '/assets/The Room No. 276 Painting.jpg' },
  { id: 'p24', category: 'paintings', title: 'Fearless Girl',  price: 690, img: '/assets/Fearless Girl Painting.jpg' },
  { id: 'p25', category: 'paintings', title: 'Light on Water',  price: 800, img: '/assets/Light on Water Painting.jpg' },
  { id: 'p26', category: 'paintings', title: 'Everlong',  price: 999, img: '/assets/Everlong Painting.jpg' },
  { id: 'p27', category: 'sculptures', title: 'Contessa',  price: 600, img: '/assets/Contessa Sculpture.jpg' },
  { id: 'p28', category: 'sculptures', title: 'Mosaic Art Palm',  price: 1100, img: '/assets/Mosaic Art Palm slp.jpg' },
  { id: 'p29', category: 'sculptures', title: 'Tang Horse',  price: 500, img: '/assets/Tang Horse Slp.jpg' },
  { id: 'p30', category: 'sculptures', title: 'Stag',  price: 1600, img: '/assets/Stag slp.jpg' },
  { id: 'p31', category: 'sculptures', title: 'Potere',  price: 1500, img: '/assets/Potere slp.jpg' },
  { id: 'p32', category: 'sculptures', title: 'Mountain Yogi',  price: 1200, img: '/assets/Mountain Yogi slp.jpg' },
  { id: 'p33', category: 'sculptures', title: 'Narciso',  price: 800, img: '/assets/Narciso slp.jpg'},
  { id: 'p16', category: 'photography', title: 'Butterfly Pause',  price: 450, img: '/assets/Butterfly Pause phg.jpg' },
  { id: 'p16', category: 'photography', title: 'Gimblet Rock',  price: 450, img: '/assets/Gimblet Rock phg.jpg' },
  { id: 'p16', category: 'photography', title: 'Torn Tree',  price: 450, img: '/assets/Torn Tree phg.jpg' },
  { id: 'p16', category: 'photography', title: 'Rapefield',  price: 450, img: '/assets/Rapefield phg.jpg' }
];
